[package]
name = "transaction_decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
serde_json = "1.0.140"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.9"
clap = { version = "4.5.40", features = ["derive"] }
